# configuration for "develop" branch (ie TESTING environment), a rolling stream of development as developers merge in their sprint features 

#========================================================================
# build and deployment of TESTING configuration
#========================================================================
-
  os: Visual Studio 2015
  
  init:
    - git config --global core.autocrlf true
  
  environment:
    Environment: Debug

  # Install scripts. (runs after repo cloning)
  install:
    - git remote set-url origin https://github.com/daleholborow/iayos.flashcards.suomi.git
    # Get the latest stable version of Node.js or io.js
    - ps: Install-Product node ''
    #- npm -g install npm@2
    - set PATH=%APPDATA%\npm;%PATH%;
    # Install global modules
    #- npm install -g gulp --skip-installed          # Gulp so we can perform build-time gulp calls to MSBuild task. Skip installation if already in cache
    - cd frontend    
    - npm install -g gulp typings --skip-installed
    - npm install --skip-installed
    - cd ..  
 
 # Post-install test scripts.
  test_script:
    # Output useful info for debugging.
    - node --version
    - npm --version
    ## run tests
    #- npm test
  
  nuget:
    account_feed: true  
  
  branches:
    only:
      - develop
      - master
      - /feature.*/   # You can use Regex expression to match multiple branch name(s)

  configuration: Debug
  
  platform: Any CPU

  # Retain NuGet, Bower & NPM package caches between builds.  
  cache:

  before_build:
    # Run Gulp build on frontend site.
    - cd frontend
    - typings install
    - gulp build
    - cd ..
    #- cd ..

    # Restore NuGet packages.
    # Because NuGet has such sporadically poor connectivity, for retries see: http://www.appveyor.com/docs/nuget#restore-with-retries 
    #- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe    
    - nuget-restore.cmd backend\iayos.flashcards.suomi.sln

  build:
    project: backend\iayos.flashcards.suomi.sln
    publish_wap: true
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    # quiet|minimal|normal|detailed
    verbosity: quiet

  artifacts:
    - path: frontend\app\
      name: final-app

  deploy:
    -
      provider: Environment
      name: iayos.flashcards.suomi

